### ISSUE TITLE
Document automatic ddck connection feature

### ISSUE THREAD

**Issue by martin-neugebauer** [SPF-OST/pytrnsys_doc#1]
We need to document the automatic ddck connection feature after its completion

- [x] Document how to export the connection.json in the section "The graphical user interface"
- [x] Document how to use the connection.json in pytrnsys in the section "Running simulations -> Simulation control"
- [x] Explain what information is given in the widget on the lower left when hovering above a port and how this relates to the placeholder statements in the section "The graphical user interface -> Component library and port information -> Port information"
- [x] Describe the syntax of the placeholder statements in "Structure of a ddck-file -> Inputs from the hydraulic solver"

**Comment by martin-neugebauer** [comment]
@zuckerruebe FYI

**Comment by PuaYongHao** [comment]
Since pathToConnectionInfo is a path, I am thinking if it is better to document how to use the connection.json in pytrnsys in the section "Running simulations -> Path"?

**Comment by martin-neugebauer** [comment]
It is indeed a path, but the function is more relevant for the simulation control, so I would put it there. The other paths are really used as paths, whereas in this case it's mainly about where to find the information about the hydraulic connections. We can still move the section about this particular feature later, if we think we know a better place.

**Comment by martin-neugebauer** [comment]
@PuaYongHao I added two more items to the list, could you work on those? Please continue on the automatic-ddck-connection branch. I added a section for the port information there.

I merged your previous additions with master, which made them public.
